# Site settings
title: Î»
email: lawrence@lawrencewu.me
description: > # this means to ignore newlines until "baseurl:"
  Lawrence's personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lawrencewu.me" # the base hostname & protocol for your site
twitter_username: lvwrencewu
github_username:  oneohtrix

# Build settings
markdown: kramdown
